### ISSUE TITLE
allow for a config file.

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#1995]
## Description

we are starting to get quite a few cli args. Most of the time users don't need, or want to set all of them, but I think it'd be a really nice addition to simply allow specifying a config file instead of passing many args through the cli. 

Additionally, there are a lot of [datafusion configuration parameters](https://arrow.apache.org/datafusion/user-guide/configs.html) that we _could_ expose for those looking to really fine tune the configuration 

We'll probably also have quite a few more configuration parameters around hybrid & distributed execution later on as well. 

I think it'd be nice to do something like this

```toml
# glaredb.toml
bind_addr = "<url>"
metastore_addr = "<string>"
data_dir = "<path>"
service_account_path = "<path>"
spill_path = "<path>"
disable_rpc_auth = true


# exposed datafusion configuration params

[planner]
explain.logical_plan_only = true

[execution]
planning_concurrency = 2

```

```
just run local --config glaredb.toml
```
